GET https://api.cloudflare.com/client/v4/user/tokens/verify
X-Auth-Email: {{$dotenv CF_AUTH_EMAIL}}
Authorization: Bearer {{$dotenv CF_AUTH_TOKEN}}
Content-Type: application/json

###

GET https://api.cloudflare.com/client/v4/zones?status=active&account.id={{$dotenv CF_ACCOUNT_ID}}&page=1&per_page=50&order=status&match=all
X-Auth-Email: {{$dotenv CF_AUTH_EMAIL}}
Authorization: Bearer {{$dotenv CF_AUTH_TOKEN}}
Content-Type: application/json

###

GET https://api.cloudflare.com/client/v4/zones/ad665cba05df759c3aa3a17e64ee825b/dns_records?type=A&page=1&per_page=100&order=type&direction=desc&match=all
X-Auth-Email: {{$dotenv CF_AUTH_EMAIL}}
Authorization: Bearer {{$dotenv CF_AUTH_TOKEN}}
Content-Type: application/json

###

PATCH https://api.cloudflare.com/client/v4/zones/70c9eca75852376266b44f202547d20d/dns_records/25b8a34e278817ddadda668c9374e01c
X-Auth-Email: {{$dotenv CF_AUTH_EMAIL}}
Authorization: Bearer {{$dotenv CF_AUTH_TOKEN}}
Content-Type: application/json

{"type":"A","name":"a.extranet.win","content":"127.0.0.2"}